[command]
command = "python run_initialize_pinecone.py && cd frontend && python app.py"
name = "Storytelling Demo"
description = "Run the Storytelling Interface with Latent Concept Models (LCM)"
icon = "storytelling"
onBoot = "pip install python-dotenv pinecone-client openai"
restartOn = {}
restartPolicy = "never"
wait_for_port = 5000
show_output = true