run = "cd frontend && python standalone_upload.py"
language = "python"
entrypoint = "frontend/standalone_upload.py"
hidden = false
persistent = true
onBoot = "wait"
wait_for_port = 7000
timeout = 180000
onPort = { action = "open", port = 7000, url_path = "/" }
environment = { 
  DEBUG = "true", 
  FLASK_ENV = "development", 
  HOST = "0.0.0.0", 
  PORT = "7000",
  REPLIT_ENVIRONMENT = "true",
  ENABLE_REPLIT_AUTH = "false",
  WERKZEUG_RUN_MAIN = "true"
}